# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='face_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
