# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20160520_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.Location'),
        ),
    ]
