# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20160520_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tweetimage',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collector.Tweet'),
        ),
        migrations.AddField(
            model_name='tweetimage',
            name='tweet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.TwitterUser'),
        ),
    ]
