# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20160521_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='image',
        ),
    ]
