# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_remove_twitteruser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
