# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hashtag',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
